services:
  postgres:
    image: postgres:15
    container_name: postgresBD
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - aifood-net
    # ⚠️ Exponha a porta APENAS em desenvolvimento, nunca em produção
    # ports:
    #   - "5431:5432"

  aifoodapp:
    build: .
    container_name: aifoodapp
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/${POSTGRES_DB}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
      SPRING_PROFILES_ACTIVE: prod
      
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
      MARITACA_API_KEY: ${MARITACA_API_KEY}
      FRONTEND_URL: ${FRONTEND_URL}
      COOKIE_SECURE: "true"
      COOKIE_DOMAIN: ".aifoodapp.site"
    ports:
      - "8080:8080"
    restart: unless-stopped
    networks:
      - aifood-net

volumes:
  postgres_data:

networks:
  aifood-net: